import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
} from '@/components/ui/card'
import { cn } from '@/lib/utils'
import type { AdapterRenderProps } from '../../types'

// Phase 6 multi-canvas Card. Each named slot (header/body/footer) is its own
// drop zone — the user composes by dropping Text/Button/etc. into each. The
// `slotChildren` map carries the <Element canvas/> wrappers generated by
// CanonicalNode; we place each in the corresponding shadcn region.
export function ShadcnCard({
  rootRef,
  composedClasses = {},
  composedInlineStyles = {},
  slotChildren = {},
}: AdapterRenderProps) {
  return (
    <Card
      ref={rootRef as never}
      className={cn(composedClasses.root)}
      style={composedInlineStyles.root}
    >
      <CardHeader
        className={cn(composedClasses.header)}
        style={composedInlineStyles.header}
      >
        {slotChildren.header}
      </CardHeader>
      <CardContent
        className={cn(composedClasses.body)}
        style={composedInlineStyles.body}
      >
        {slotChildren.body}
      </CardContent>
      <CardFooter
        className={cn(composedClasses.footer)}
        style={composedInlineStyles.footer}
      >
        {slotChildren.footer}
      </CardFooter>
    </Card>
  )
}
