import path from 'node:path'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import dts from 'vite-plugin-dts'
import { visualizer } from 'rollup-plugin-visualizer'

// Phase 15 § 12.3 — `npm run analyze` sets ANALYZE=1 to emit an
// interactive treemap of the dist bundle (dist-lib/stats.html) so bundle
// growth (and which dep — e.g. MUI — dominates a chunk) is inspectable.
// Off for normal builds.
const ANALYZE = process.env.ANALYZE === '1'

// Dist build configuration. Used by `npm run build:dist` to produce an
// embeddable bundle for integration consumers and the npm-publish artifact.
//
// Two entry points (Phase 10 § 2.1):
//   - `dist-lib/index.js` — the full editor (re-exports from main-app.tsx).
//     Consumed via `import 'crafted-design-editor'`.
//   - `dist-lib/sdk.js` — the SDK surface only (no editor UI; just types
//     + register* helpers + hooks). Consumed via
//     `import { registerAdapter } from 'crafted-design-editor/sdk'`.
//
// Subpath exports in package.json route consumers to the right artifact.
// The SDK subpath has no @mui/material peer requirement because the
// SDK bundle itself doesn't reach into the editor's MUI bridge.
//
// Externals: React + React DOM + @craftjs/core are marked as peer
// dependencies — the host React app provides them. Bundling them would
// risk the "two copies of React" hook-call error.
//
// TypeScript declarations: vite-plugin-dts emits matching `.d.ts` files
// alongside each entry (`dist-lib/index.d.ts`, `dist-lib/sdk.d.ts` + the
// reachable internal types). `bundledPackages` keeps types from
// dependencies that get inlined; `entryRoot: 'src'` ensures the emitted
// `.d.ts` tree shape mirrors `src/`.

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    dts({
      // Each entry gets its own bundled .d.ts at the top level
      // (index.d.ts, sdk.d.ts). Internal type files land under
      // dist-lib/types/ via Vite's default layout.
      entryRoot: 'src',
      include: ['src/**/*.ts', 'src/**/*.tsx'],
      // The dogfood app (main.tsx, App.tsx) doesn't need declarations;
      // SDK and main-app entries do.
      exclude: ['src/**/*.test.ts', 'src/**/*.test.tsx', 'src/main.tsx'],
      // Emit a rollup-bundled .d.ts per entry so consumers see one
      // declaration file per import path.
      rollupTypes: true,
      tsconfigPath: './tsconfig.app.json',
    }),
    ...(ANALYZE
      ? [
          visualizer({
            // Repo root (not dist-lib) so it never lands in the published
            // files; gitignored.
            filename: 'bundle-stats.html',
            gzipSize: true,
            brotliSize: true,
            template: 'treemap',
          }),
        ]
      : []),
  ],
  resolve: {
    // Array form so the use-sync-external-store shim can be matched EXACTLY
    // (a string/prefix alias would also catch `…/shim/with-selector`).
    alias: [
      {
        find: '@design/sdk',
        replacement: path.resolve(__dirname, './src/sdk/index.ts'),
      },
      // Drop the CJS use-sync-external-store shim (it `require`s React, which
      // breaks pure-ESM consumers) in favor of React 19's native hook.
      {
        find: /^use-sync-external-store\/shim$/,
        replacement: path.resolve(
          __dirname,
          './src/shims/use-sync-external-store-shim.ts',
        ),
      },
      { find: '@', replacement: path.resolve(__dirname, './src') },
    ],
  },
  build: {
    outDir: 'dist-lib',
    emptyOutDir: true,
    lib: {
      // Two named entries. Vite produces dist-lib/index.js + dist-lib/sdk.js
      // with their respective .d.ts files generated by vite-plugin-dts.
      entry: {
        // Batteries-included full entry (editor + shadcn + MUI).
        index: path.resolve(__dirname, 'src/main-app.tsx'),
        // Phase 16 § 8.3 — lean entry: editor + shadcn, no MUI/Chakra.
        core: path.resolve(__dirname, 'src/core.tsx'),
        // Opt-in adapter registration entries (side-effect imports). Shared
        // editor/registry code is hoisted into a common chunk so the
        // adapter registry singleton is shared across all entries.
        'adapters/shadcn': path.resolve(__dirname, 'src/adapters/shadcn/index.ts'),
        'adapters/mui': path.resolve(__dirname, 'src/adapters/mui/index.ts'),
        'adapters/html': path.resolve(__dirname, 'src/adapters/html/index.ts'),
        sdk: path.resolve(__dirname, 'src/sdk/index.ts'),
        // Phase 21 — headless build/edit/validate/introspect for documents
        // (no React/DOM/Craft). Registers canonicals+themes+templates on
        // import; consumed by the MCP server and server-side tooling.
        headless: path.resolve(__dirname, 'src/headless/index.ts'),
        // Phase 21 — standalone runtime renderer for saved documents
        // (production pages; no editor chrome).
        renderer: path.resolve(__dirname, 'src/renderer/index.ts'),
        // Phase 12 § 4.1 — optional, node-only build-time safelist plugin.
        // Separate entry (not in the browser SDK) since it imports node:fs.
        'vite-plugin': path.resolve(__dirname, 'src/vite/safelistPlugin.ts'),
        // Phase 20 — the scaffolding CLI (`bin`). Node-only; templates are
        // copied to dist-lib/cli-templates by scripts/copy-cli-templates.ts.
        cli: path.resolve(__dirname, 'src/cli/index.ts'),
      },
      formats: ['es'],
      // Vite already emits CSS at `index.css` for the full editor entry;
      // the SDK entry's CSS is empty (it has no styles of its own).
      cssFileName: 'index',
    },
    rollupOptions: {
      // React + ReactDOM + Craft are peer dependencies — the integration host
      // supplies them. Without externalization, the dist ships its own copies
      // and React throws "Invalid hook call" at runtime due to two parallel
      // React instances seeing the same Hooks dispatcher.
      external: [
        'react',
        'react/jsx-runtime',
        'react-dom',
        'react-dom/client',
        // Phase 21 — the headless static renderer imports the server
        // renderer; bundling it would inline ~1MB of React internals (and
        // reintroduce a CJS `require("react")` into the ESM output).
        'react-dom/server',
        '@craftjs/core',
        // Phase 16 § 8.3 — the heavy UI libraries are OPTIONAL peer
        // dependencies, externalized rather than bundled. The MUI adapter
        // entry imports them (the consumer installs them only if they use
        // that adapter); `/core` never imports them. Regexes cover the
        // deep subpath imports (@mui/material/Button, etc.).
        /^@mui\//,
        /^@emotion\//,
        /^@chakra-ui\//,
        // The optional Vite plugin entry is node-only — keep `vite` and node
        // builtins external rather than bundling them into the package.
        'vite',
        /^node:/,
      ],
      output: {
        // Phase 20 — the CLI entry is an executable; prepend a shebang to
        // cli.js only (the package `bin` points at it). Other entries are
        // libraries imported by bundlers and must NOT carry a shebang.
        banner: (chunk) =>
          chunk.fileName === 'cli.js' ? '#!/usr/bin/env node' : '',
      },
    },
    // Don't minify by default — easier to debug post-install. Hosts that want
    // a minified copy can run their own bundler over our dist (esbuild,
    // Rollup, Webpack, etc.).
    minify: false,
    sourcemap: true,
  },
})
