import path from 'node:path'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import dts from 'vite-plugin-dts'

// Dist build configuration. Used by `npm run build:dist` to produce an
// embeddable bundle for integration consumers and the npm-publish artifact.
//
// Two entry points (Phase 10 § 2.1):
//   - `dist-lib/index.js` — the full editor (re-exports from main-app.tsx).
//     Consumed via `import 'crafted-design-editor'`.
//   - `dist-lib/sdk.js` — the SDK surface only (no editor UI; just types
//     + register* helpers + hooks). Consumed via
//     `import { registerAdapter } from 'crafted-design-editor/sdk'`.
//
// Subpath exports in package.json route consumers to the right artifact.
// The SDK subpath has no @mui/material peer requirement because the
// SDK bundle itself doesn't reach into the editor's MUI bridge.
//
// Externals: React + React DOM + @craftjs/core are marked as peer
// dependencies — the host React app provides them. Bundling them would
// risk the "two copies of React" hook-call error.
//
// TypeScript declarations: vite-plugin-dts emits matching `.d.ts` files
// alongside each entry (`dist-lib/index.d.ts`, `dist-lib/sdk.d.ts` + the
// reachable internal types). `bundledPackages` keeps types from
// dependencies that get inlined; `entryRoot: 'src'` ensures the emitted
// `.d.ts` tree shape mirrors `src/`.

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    dts({
      // Each entry gets its own bundled .d.ts at the top level
      // (index.d.ts, sdk.d.ts). Internal type files land under
      // dist-lib/types/ via Vite's default layout.
      entryRoot: 'src',
      include: ['src/**/*.ts', 'src/**/*.tsx'],
      // The dogfood app (main.tsx, App.tsx) doesn't need declarations;
      // SDK and main-app entries do.
      exclude: ['src/**/*.test.ts', 'src/**/*.test.tsx', 'src/main.tsx'],
      // Emit a rollup-bundled .d.ts per entry so consumers see one
      // declaration file per import path.
      rollupTypes: true,
      tsconfigPath: './tsconfig.app.json',
    }),
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      '@design/sdk': path.resolve(__dirname, './src/sdk/index.ts'),
    },
  },
  build: {
    outDir: 'dist-lib',
    emptyOutDir: true,
    lib: {
      // Two named entries. Vite produces dist-lib/index.js + dist-lib/sdk.js
      // with their respective .d.ts files generated by vite-plugin-dts.
      entry: {
        index: path.resolve(__dirname, 'src/main-app.tsx'),
        sdk: path.resolve(__dirname, 'src/sdk/index.ts'),
      },
      formats: ['es'],
      // Vite already emits CSS at `index.css` for the full editor entry;
      // the SDK entry's CSS is empty (it has no styles of its own).
      cssFileName: 'index',
    },
    rollupOptions: {
      // React + ReactDOM + Craft are peer dependencies — the integration host
      // supplies them. Without externalization, the dist ships its own copies
      // and React throws "Invalid hook call" at runtime due to two parallel
      // React instances seeing the same Hooks dispatcher.
      external: [
        'react',
        'react/jsx-runtime',
        'react-dom',
        'react-dom/client',
        '@craftjs/core',
      ],
    },
    // Don't minify by default — easier to debug post-install. Hosts that want
    // a minified copy can run their own bundler over our dist (esbuild,
    // Rollup, Webpack, etc.).
    minify: false,
    sourcemap: true,
  },
})
