// Public SDK — per-canonical prop types (Phase 18 § 5).
//
// Adapter authors implementing a canonical's renderer need its prop type to
// type the `props` they receive (e.g. `props as ButtonProps`). Re-exported
// here so they import from the SDK boundary, not `@/registry/components/*`.
// Type-only — erased at runtime, so this carries no bundle / freeze cost.

export type { AlertProps } from '../registry/components/alert'
export type { AudioProps } from '../registry/components/audio'
export type { AvatarProps } from '../registry/components/avatar'
export type { BadgeProps } from '../registry/components/badge'
export type { BoxProps } from '../registry/components/box'
export type { BreadcrumbProps } from '../registry/components/breadcrumb'
export type { ButtonProps } from '../registry/components/button'
export type { CardProps } from '../registry/components/card'
export type { CarouselProps } from '../registry/components/carousel'
export type { CheckboxProps } from '../registry/components/checkbox'
export type { CodeProps } from '../registry/components/code'
export type { ContainerProps } from '../registry/components/container'
export type { DataListItemProps } from '../registry/components/data-list-item'
export type { DataListProps } from '../registry/components/data-list'
export type { DatePickerProps } from '../registry/components/date-picker'
export type { DateRangePickerProps } from '../registry/components/date-range-picker'
export type { DividerProps } from '../registry/components/divider'
export type { DrawerProps } from '../registry/components/drawer'
export type { GridProps } from '../registry/components/grid'
export type { HeadingProps } from '../registry/components/heading'
export type { IconProps } from '../registry/components/icon'
export type { ImageProps } from '../registry/components/image'
export type { InputProps } from '../registry/components/input'
export type { LinkProps } from '../registry/components/link'
export type { ModalProps } from '../registry/components/modal'
export type { NavItemProps } from '../registry/components/nav-item'
export type { NavMenuProps } from '../registry/components/nav-menu'
export type { PaginationProps } from '../registry/components/pagination'
export type { PopoverProps } from '../registry/components/popover'
export type { ProgressProps } from '../registry/components/progress'
export type { RadioProps } from '../registry/components/radio'
export type { SectionProps } from '../registry/components/section'
export type { SelectProps } from '../registry/components/select'
export type { SkeletonProps } from '../registry/components/skeleton'
export type { SpacerProps } from '../registry/components/spacer'
export type { SpinnerProps } from '../registry/components/spinner'
export type { StackProps } from '../registry/components/stack'
export type { StepperProps } from '../registry/components/stepper'
export type { SwitchProps } from '../registry/components/switch'
export type { TableCellProps } from '../registry/components/table-cell'
export type { TableProps } from '../registry/components/table'
export type { TabsProps } from '../registry/components/tabs'
export type { TextProps } from '../registry/components/text'
export type { TextareaProps } from '../registry/components/textarea'
export type { TimePickerProps } from '../registry/components/time-picker'
export type { ToastProps } from '../registry/components/toast'
export type { TooltipProps } from '../registry/components/tooltip'
export type { VideoProps } from '../registry/components/video'
