/**
 * Phase 16 § 7.3 — adapter compatibility matrix.
 *
 * Introspects every registered adapter × the canonical registry and emits a
 * coverage table: which canonicals each adapter implements, grouped by
 * category. The missing-renderer placeholder is the runtime fallback for any
 * gap, so a partial adapter (the Chakra *example*) is valid — it just won't
 * render the canonicals it omits.
 *
 * Run `tsx scripts/adapter-matrix.ts` to print the table and (re)write
 * `docs/ADAPTER_MATRIX.md`. Pass `--check` (CI) to additionally fail when a
 * BUILT-IN adapter (shadcn / mui / html) has a gap — the published package
 * promises 100% built-in coverage, so a gap there is drift, not a choice.
 * The Chakra example is expected partial and only ever warns.
 *
 * This complements the unit guard in `adapters-register.test.ts` (which
 * asserts the three built-ins cover an identical id set) with a
 * human-readable, docs-committed view that also includes the example adapter.
 */
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

// Side-effect imports register the canonicals + adapters into the shared
// singletons. Order doesn't matter — registration is idempotent by id.
import '@/registry/components'
import '@/adapters/shadcn'
import '@/adapters/mui'
import '@/adapters/html'
// The example adapter ships under examples/, not in the package. Including it
// proves the matrix surfaces intentional gaps (and the placeholder fallback).
import '../examples/adapter-chakra'

import { listAdapters } from '@/adapters/AdapterContext'
import { listComponents } from '@/registry/registry'
import type { CanonicalCategory } from '@/registry/types'

const BUILTIN_ADAPTER_IDS = ['shadcn', 'mui', 'html']

const CATEGORY_ORDER: CanonicalCategory[] = [
  'layout',
  'content',
  'input',
  'display',
  'navigation',
  'feedback',
  'media',
]

const DOC_PATH = resolve(import.meta.dirname, '..', 'docs', 'ADAPTER_MATRIX.md')

const checkMode = process.argv.includes('--check')

const canonicals = [...listComponents()].sort(
  (a, b) =>
    CATEGORY_ORDER.indexOf(a.category) - CATEGORY_ORDER.indexOf(b.category) ||
    a.id.localeCompare(b.id),
)
const adapters = listAdapters()

const covers = (adapterId: string, canonicalId: string): boolean => {
  const a = adapters.find((x) => x.id === adapterId)
  return !!a && canonicalId in a.components
}

const coverage = (adapterId: string): number =>
  canonicals.filter((c) => covers(adapterId, c.id)).length

// ── Build the Markdown table ────────────────────────────────────────────────
const header = ['Canonical', 'Category', ...adapters.map((a) => a.displayName)]
const sep = header.map(() => '---')

const rows: string[][] = []
let lastCategory = ''
for (const c of canonicals) {
  const category = c.category === lastCategory ? '' : c.category
  lastCategory = c.category
  rows.push([
    `\`${c.id}\``,
    category,
    ...adapters.map((a) => (covers(a.id, c.id) ? '✅' : '—')),
  ])
}

const summary = [
  '**Coverage**',
  '',
  ...adapters.map((a) => `${coverage(a.id)} / ${canonicals.length}`),
]

const toRow = (cells: string[]) => `| ${cells.join(' | ')} |`

// Phase 16 § 7.4 — peer-dependency rows: each adapter's declared external npm
// peers → tested semver range. Adapters with none (shadcn, html) read "none".
const peerRows = adapters.map((a) => {
  const peers = a.peerDependencies ?? {}
  const entries = Object.entries(peers)
  const cell = entries.length
    ? entries.map(([pkg, range]) => `\`${pkg}\` ${range}`).join('<br>')
    : 'none'
  return [a.displayName, `\`${a.id}\``, cell]
})

const md = `<!-- GENERATED by scripts/adapter-matrix.ts — do not edit by hand. -->
# Adapter compatibility matrix

Which canonical components each registered adapter implements. ✅ = a real
renderer; — = no renderer, so the editor falls back to the missing-renderer
placeholder for that canonical under that adapter.

The three **built-in** adapters (\`shadcn\`, \`mui\`, \`html\`) ship in the package
and cover **100%** of the registry. \`chakra-example\` lives under \`examples/\`
and is intentionally partial — a reference for authoring your own adapter, not
a complete one.

${toRow(header)}
${toRow(sep)}
${rows.map(toRow).join('\n')}
${toRow(summary)}

## Peer dependencies

The npm packages each adapter needs the host to install, mapped to the semver
range it's tested against. These are **optional** peers — a host installs only
the peers for the adapters it imports (see \`package.json\`
\`peerDependenciesMeta\`). \`shadcn\` and \`html\` need none (they use the package's
own deps). See [ADAPTER_VERSIONING.md](./ADAPTER_VERSIONING.md) for the policy.

${toRow(['Adapter', 'id', 'Peer dependencies (tested range)'])}
${toRow(['---', '---', '---'])}
${peerRows.map(toRow).join('\n')}

Regenerate with \`npm run docs:matrix\`. CI runs \`npm run docs:matrix -- --check\`,
which fails if a built-in adapter ever drops below full coverage.
`

writeFileSync(DOC_PATH, md)

// ── Console report ──────────────────────────────────────────────────────────
const pad = (s: string, n: number) => s.padEnd(n)
const idW = Math.max(...canonicals.map((c) => c.id.length), 9)
const colW = adapters.map((a) => Math.max(a.id.length, 4))

console.log(`\nAdapter compatibility matrix — ${canonicals.length} canonicals\n`)
console.log(
  pad('canonical', idW),
  ...adapters.map((a, i) => pad(a.id, colW[i])),
)
for (const c of canonicals) {
  console.log(
    pad(c.id, idW),
    ...adapters.map((a, i) => pad(covers(a.id, c.id) ? '✓' : '·', colW[i])),
  )
}
console.log(
  '\n' + pad('coverage', idW),
  ...adapters.map((a, i) => pad(`${coverage(a.id)}/${canonicals.length}`, colW[i])),
)
console.log('\npeer dependencies:')
for (const a of adapters) {
  const peers = Object.entries(a.peerDependencies ?? {})
  console.log(
    `  ${pad(a.id, 16)} ${peers.length ? peers.map(([p, r]) => `${p}@${r}`).join(', ') : 'none'}`,
  )
}
console.log(`\nWrote ${DOC_PATH}\n`)

// ── Drift guard ───────────────────────────────────────────────────────────────
const gaps: string[] = []
for (const id of BUILTIN_ADAPTER_IDS) {
  const missing = canonicals.filter((c) => !covers(id, c.id)).map((c) => c.id)
  if (missing.length) gaps.push(`  ${id}: missing ${missing.join(', ')}`)
}

if (gaps.length) {
  const msg = `Built-in adapters must cover every canonical:\n${gaps.join('\n')}`
  if (checkMode) {
    console.error(`\n✗ ${msg}\n`)
    process.exit(1)
  }
  console.warn(`\n⚠ ${msg}\n`)
} else if (checkMode) {
  console.log('✓ all built-in adapters cover every canonical\n')
}
