/**
 * Phase 20 — component gallery (deployed at /gallery).
 *
 * A static, browsable catalog of every canonical grouped by category, each
 * with its tags and a per-adapter coverage row (which design systems render
 * it). Complements the live /try editor (which renders everything
 * interactively) and the machine-checked docs/ADAPTER_MATRIX.md with a visual
 * index. Reuses the registry introspection from adapter-matrix.ts.
 *
 * Run `npm run build:gallery` → dist-gallery/index.html.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

// Side-effect imports populate the shared registry singletons.
import '@/registry/components'
import '@/adapters/shadcn'
import '@/adapters/mui'
import '@/adapters/html'
import '../examples/adapter-chakra'

import { listAdapters } from '@/adapters/AdapterContext'
import { listComponents } from '@/registry/registry'
import type { CanonicalCategory } from '@/registry/types'

const OUT_DIR = resolve(import.meta.dirname, '..', 'dist-gallery')
const AVATAR = 'https://avatars.githubusercontent.com/u/19990046'

const CATEGORY_ORDER: CanonicalCategory[] = [
  'layout',
  'content',
  'input',
  'display',
  'navigation',
  'feedback',
  'media',
]
const CATEGORY_LABEL: Record<string, string> = {
  layout: 'Layout',
  content: 'Content',
  input: 'Input',
  display: 'Display',
  navigation: 'Navigation',
  feedback: 'Feedback',
  media: 'Media',
}

const esc = (s: string) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

const adapters = listAdapters()
const canonicals = [...listComponents()]
  .filter((c) => !c.hidden)
  .sort(
    (a, b) =>
      CATEGORY_ORDER.indexOf(a.category) - CATEGORY_ORDER.indexOf(b.category) ||
      a.displayName.localeCompare(b.displayName),
  )

const covers = (adapterId: string, canonicalId: string): boolean => {
  const a = adapters.find((x) => x.id === adapterId)
  return !!a && canonicalId in a.components
}

// Group canonicals by category, preserving CATEGORY_ORDER.
const byCategory = new Map<string, typeof canonicals>()
for (const c of canonicals) {
  const list = byCategory.get(c.category) ?? []
  list.push(c)
  byCategory.set(c.category, list)
}

function card(c: (typeof canonicals)[number]): string {
  const chips = adapters
    .map((a) => {
      const ok = covers(a.id, c.id)
      return `<span class="chip ${ok ? 'on' : 'off'}" title="${esc(a.displayName)}">${esc(
        a.displayName,
      )} ${ok ? '✓' : '—'}</span>`
    })
    .join('')
  const tags = c.tags
    .slice(0, 4)
    .map((t) => `<span class="tag">${esc(t)}</span>`)
    .join('')
  return `<article class="card">
    <div class="card-head">
      <h3>${esc(c.displayName)}</h3>
      <code class="cid">${esc(c.id)}</code>
    </div>
    ${tags ? `<div class="tags">${tags}</div>` : ''}
    <div class="chips">${chips}</div>
  </article>`
}

const sections = CATEGORY_ORDER.filter((cat) => byCategory.has(cat))
  .map(
    (cat) => `<section class="cat">
    <h2>${esc(CATEGORY_LABEL[cat] ?? cat)} <span class="count">${byCategory.get(cat)!.length}</span></h2>
    <div class="grid">${byCategory.get(cat)!.map(card).join('')}</div>
  </section>`,
  )
  .join('\n')

const builtIns = adapters.filter((a) => ['shadcn', 'mui', 'html'].includes(a.id))
const fullCount = builtIns.filter(
  (a) => canonicals.filter((c) => covers(a.id, c.id)).length === canonicals.length,
).length

const html = `<!doctype html>
<!-- GENERATED by scripts/build-gallery.ts — run \`npm run build:gallery\`. -->
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Component gallery · crafted-design</title>
<meta name="description" content="Every canonical component in crafted-design, grouped by category, with per-adapter (shadcn, MUI, plain HTML) coverage." />
<link rel="icon" href="${AVATAR}" />
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,500;9..144,600&family=Hanken+Grotesk:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet" />
<style>
:root{
  --paper:#faf6ef;--panel:#fffdf9;--ink:#211c15;--ink-soft:#5f564a;--ink-faint:#8a8073;
  --line:#e7ddca;--accent:#bd4a2b;--accent-deep:#9c3a20;--accent-tint:#f6e2d6;--ok:#3f7d57;
  --sans:"Hanken Grotesk",ui-sans-serif,system-ui,sans-serif;--serif:"Fraunces",Georgia,serif;--mono:"JetBrains Mono",ui-monospace,monospace;
}
*{box-sizing:border-box}
body{margin:0;background:var(--paper);color:var(--ink);font-family:var(--sans);line-height:1.6;background-image:radial-gradient(#efe7d6 .5px,transparent .5px);background-size:22px 22px}
a{color:var(--accent);text-decoration:none}a:hover{color:var(--accent-deep);text-decoration:underline}
.wrap{max-width:74rem;margin:0 auto;padding:0 1.5rem 6rem}
header.hero{padding:3.5rem 0 2rem;border-bottom:1px solid var(--line);display:flex;align-items:center;gap:1rem}
.hero img{width:44px;height:44px;border-radius:50%;border:1px solid var(--line)}
.hero h1{font-family:var(--serif);font-weight:600;font-size:2.3rem;letter-spacing:-.02em;margin:0}
.hero p{margin:.3rem 0 0;color:var(--ink-soft);font-size:1.02rem}
.crumbs{padding:1rem 0 0;font-size:.9rem}
.legend{display:flex;flex-wrap:wrap;gap:.5rem;padding:1.4rem 0 .5rem;color:var(--ink-faint);font-size:.8rem;align-items:center}
.cat{padding:2rem 0 .5rem}
.cat h2{font-family:var(--serif);font-weight:600;font-size:1.6rem;margin:0 0 1rem;letter-spacing:-.015em}
.cat h2 .count{font-family:var(--mono);font-size:.85rem;color:var(--ink-faint);font-weight:400;margin-left:.4rem}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(15rem,1fr));gap:.9rem}
.card{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:.9rem 1rem 1rem;box-shadow:0 10px 30px -24px rgba(33,28,21,.5)}
.card-head{display:flex;align-items:baseline;justify-content:space-between;gap:.5rem}
.card h3{font-family:var(--serif);font-weight:600;font-size:1.12rem;margin:0}
.cid{font-family:var(--mono);font-size:.7rem;color:var(--ink-faint)}
.tags{display:flex;flex-wrap:wrap;gap:.3rem;margin:.45rem 0 .6rem}
.tag{font-size:.66rem;color:var(--ink-soft);background:var(--accent-tint);border-radius:5px;padding:.05rem .4rem}
.chips{display:flex;flex-wrap:wrap;gap:.3rem;margin-top:.5rem;border-top:1px solid var(--line);padding-top:.6rem}
.chip{font-family:var(--mono);font-size:.66rem;border-radius:5px;padding:.1rem .42rem;border:1px solid var(--line)}
.chip.on{color:var(--ok);border-color:color-mix(in oklch,var(--ok) 35%,var(--line))}
.chip.off{color:var(--ink-faint);opacity:.7}
footer{margin-top:3rem;padding-top:1.5rem;border-top:1px solid var(--line);color:var(--ink-faint);font-size:.85rem}
</style>
</head>
<body>
<div class="wrap">
  <header class="hero">
    <img src="${AVATAR}" alt="" width="44" height="44" loading="lazy" />
    <div>
      <h1>Component gallery</h1>
      <p>${canonicals.length} canonical components · ${adapters.length} adapters · ${fullCount}/${builtIns.length} built-ins at full coverage</p>
    </div>
  </header>
  <nav class="crumbs"><a href="../">← Docs</a> · <a href="../try/">Try it live →</a></nav>
  <div class="legend">
    <span>Coverage:</span>
    <span class="chip on">adapter ✓</span> renders it ·
    <span class="chip off">adapter —</span> falls back to a placeholder
  </div>
  ${sections}
  <footer>One canonical model, many design systems. See <a href="../#integration">the integration guide</a> to embed the editor, or <a href="../#tutorial-adapter">author your own adapter</a>.</footer>
</div>
</body>
</html>
`

mkdirSync(OUT_DIR, { recursive: true })
writeFileSync(resolve(OUT_DIR, 'index.html'), html)
const kb = (Buffer.byteLength(html) / 1024).toFixed(0)
console.log(
  `Built gallery → ${resolve(OUT_DIR, 'index.html')}\n  ${canonicals.length} canonicals × ${adapters.length} adapters, ${kb} KB.`,
)
