/**
 * Generates `src/style/safelist.generated.css` from the slice arrays in
 * `src/style/tw-classes.ts`.
 *
 * Why: Tailwind v4's JIT only compiles utilities it sees as *literal* class
 * strings in scanned source. Inspector panels build classes via template
 * literals (`text-${size}`, `bg-${color}`, …) which the scanner can't see —
 * the classes land in the DOM but Tailwind generates no CSS for them.
 *
 * Solution: declare every utility this app can produce inside an `@source
 * inline()` block in CSS. Tailwind reads those directives and compiles the
 * listed classes regardless of whether it sees them in source.
 *
 * Multiplier: each utility family is emitted at base + 5 breakpoint prefixes
 * (sm/md/lg/xl/2xl) so the responsive bar's edits work at any breakpoint.
 *
 * Wire-up: `npm run gen-safelist` runs this. `predev` and `prebuild` hooks
 * call it. Output file is gitignored.
 */
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

import {
  // typography
  FONT_SIZES, FONT_WEIGHTS, TEXT_ALIGNS, BUILTIN_FONT_FAMILIES,
  // shared
  COLORS,
  // layout
  DISPLAYS, FLEX_DIRS, ITEMS, JUSTIFY, GAPS,
  // spacing
  SPACING_VALUES, SPACING_PREFIXES,
  // size
  SIZE_VALUES, SIZE_PREFIXES,
  // appearance
  BORDER_WIDTHS, BORDER_STYLES, RADII,
  // effects
  SHADOWS, OPACITIES, BLURS,
} from '../src/style/tw-classes'

const OUTPUT_PATH = resolve(import.meta.dirname, '../src/style/safelist.generated.css')

// Variant prefixes we safelist every family under:
//   - '' + the 5 Tailwind breakpoints  → responsive (base state)
//   - Phase 12 § 4.2: hover/focus/active → pseudo-class states (base bp)
// We deliberately do NOT emit the breakpoint × state cross-product
// (`md:hover:…`) to bound CSS growth: that rarer combo is shown in the
// editor via the canvas state-preview (unprefixed) and resolved in
// production by the host's build-time safelist plugin (Phase 12 § 4.1).
const VARIANTS = [
  '',
  'sm:',
  'md:',
  'lg:',
  'xl:',
  '2xl:',
  'hover:',
  'focus:',
  'active:',
] as const

// Emits one `@source inline()` per variant for a single utility family.
//   emit('text-', FONT_SIZES) →
//     @source inline("text-{xs,sm,…}");
//     @source inline("sm:text-{xs,sm,…}");
//     …
//     @source inline("hover:text-{xs,sm,…}");
//     …
function emit(prefix: string, values: readonly string[]): string[] {
  if (values.length === 0) return []
  const list = values.join(',')
  return VARIANTS.map((v) => `@source inline("${v}${prefix}{${list}}");`)
}

// For bare utilities (no value suffix) — `flex`, `block`, `border`, etc.
function emitBare(...classes: string[]): string[] {
  if (classes.length === 0) return []
  const list = classes.join(',')
  return VARIANTS.map((v) => `@source inline("${v}{${list}}");`)
}

const lines: string[] = [
  '/* ============================================================================',
  '   AUTO-GENERATED by scripts/gen-safelist.ts — do not edit.',
  '   Source of truth: src/style/tw-classes.ts slice arrays.',
  '   Regenerate via `npm run gen-safelist` (also runs on `npm run dev` / `build`).',
  '   ============================================================================ */',
  '',
  '/* Typography */',
  ...emit('text-', FONT_SIZES),
  ...emit('font-', FONT_WEIGHTS),
  // Phase 8 — built-in font-family ids (sans, heading, mono). User-registered
  // ids inject their own .font-<id> rule at runtime, so they don't need to
  // be in the safelist.
  ...emit('font-', BUILTIN_FONT_FAMILIES),
  ...emit('text-', TEXT_ALIGNS),
  ...emit('text-', COLORS),
  '',
  '/* Layout */',
  ...emitBare(...DISPLAYS),
  ...emit('flex-', FLEX_DIRS),
  ...emit('items-', ITEMS),
  ...emit('justify-', JUSTIFY),
  ...emit('gap-', GAPS),
  '',
  '/* Spacing — 14 prefixes × spacing values */',
  ...SPACING_PREFIXES.flatMap((p) => emit(`${p}-`, SPACING_VALUES)),
  '',
  '/* Size — 6 prefixes × size values */',
  ...SIZE_PREFIXES.flatMap((p) => emit(`${p}-`, SIZE_VALUES)),
  '',
  '/* Appearance */',
  ...emit('bg-', COLORS),
  ...emitBare('border'),                       // default border width (1px)
  ...emit('border-', BORDER_WIDTHS),
  ...emit('border-', BORDER_STYLES),
  ...emit('border-', COLORS),
  ...emitBare('rounded'),                      // default radius
  ...emit('rounded-', RADII),
  '',
  '/* Effects */',
  ...emitBare('shadow'),                       // default shadow
  ...emit('shadow-', SHADOWS),
  ...emit('opacity-', OPACITIES),
  ...emitBare('blur'),                         // default blur (legacy Effects)
  ...emit('blur-', BLURS),
  // Phase 12 — Transforms / Filters / Transitions are authored as
  // INLINE CSS (composed `transform` / `filter` strings + transition
  // longhands), NOT Tailwind classes, so they need no safelist entries.
  // See src/style/cssFunctions.ts for why (custom values + single-
  // property composition).
  '',
  '/* Phase 5 — one-off utilities for new canonical defaults */',
  // Image aspect ratios + Link's underline-offset-4 + object-fit for images.
  ...emitBare('aspect-auto', 'aspect-square', 'aspect-video'),
  ...emitBare('underline-offset-4'),
  ...emitBare('object-cover', 'object-contain'),
  '',
]

writeFileSync(OUTPUT_PATH, lines.join('\n'), 'utf8')

const directiveCount = lines.filter((l) => l.startsWith('@source')).length
console.log(`[gen-safelist] wrote ${OUTPUT_PATH}`)
console.log(`[gen-safelist] emitted ${directiveCount} @source directives`)
